### ISSUE TITLE
possibility to open from string or StringIO instead of file.

### ISSUE THREAD

**Issue by carichte** [kif/fabio#28]
Dear all,

for some reason, I already have the image opened and the content in form of a string before passing it to fabio. There I write the content to a file to be able to open it again.
Is there a way to directly pass the string or a StringIO object to fabio? Up to now it wasn't obvious how to do it yet. If not.. can it be implemented with reasonable efforts?

**Comment by kif** [comment]
On Mon, 06 Jul 2015 04:49:57 -0700
Carsten Richter <notifications@github.com> wrote:

> for some reason, I already have the image opened and the content in form of a string before passing it to fabio. There I write the content to a file to be able to open it again.
> Is there a way to directly pass the string or a StringIO object to fabio? Up to now it wasn't obvious how to do it yet. If not.. can it be implemented with reasonable efforts?

Dear Carsten,

I think it should be possible by calling directly the read method of a fabioimage instance but it is obviously broken.

I will investigate.

Cheers,
Jérôme

**Comment by jonwright** [comment]
Hi,

I think it used to work.

The lines saying hasattr(fname,"read") and "write" in fabioimage._open 
just need to come before the lines about filename and filenumber. 
fabioimage._open was supposed to accept file-like objects but it was 
broken in [r5388] of the old svn when filenumber was added. This should 
probably be zero or None(?) in the case of a StringIO object.

And then of course elsewhere in the code the classes need to be using 
self._open instead of opening files directly, but most of them do that 
already to handle gzip etc.

Cheers

Jon

**Comment by carichte** [comment]
Hi,

thanks for the quick response. It works now. 
Instead of StringIO one needs to use io.BytesIO, because otherwise the `with` statement (in OXDimage.read) doesn't accept it due to a lack of the __exit__ method.
StringIO.StringIO seems outdated and io.StringIO is used for unicode instead.

Thanks 
Carsten

**Comment by kif** [comment]
This  should be fixed now.
If you don't provide a "fabio.fabioutils.BytesIO" object, your data will be copied.
